import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Map from "./components/Map"
import Navbar from './components/Navbar'
import Image from 'next/image'
const inter = Inter({ subsets: ['latin'] })
export default function Home() {
  return (
    <>
      <Head>
        <title>Public Art San Antonio</title>
        <link rel="icon" href="./alamo.png" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta charset="utf-8" />
       <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Navbar/>

      <main className={`${styles.main}`}>
          <h1>Public Art San Antonio</h1>
          <div  className='image-container'>
          <Image src="/images/Banner.png" alt="banner" className= "banner" width={700} height={200} />
          </div>
        <div className="map-container">
          <Map/>
        </div>
       
      </main>
    </>
  )
}
