import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Map from "./components/Map"
import Image from 'next/image'
import { motion } from "framer-motion";


const inter = Inter({ subsets: ['latin'] })
export default function Home() {
  return (
    <>
      <Head>
        <link rel="icon" href="./alamo.png" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

      </Head>
      <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.5 }}
          >
      <main className={`${styles.main}`}>
        <motion.h1
          initial={{ opacity: 0, y: -50 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 1 }}
          className='banner-txt'
        >
          Public Art San Antonio
        </motion.h1>
        <div className='image-container'>
          <Image src="/images/Banner.png" alt="banner" className="banner" width={700} height={200} />
        </div>
        <div className="map-container">
          <Map />
        </div>

      </main>
      </motion.div>
    </>
  )
}
